<?php

namespace App\Controller;

use App\Entity\Media;
use App\Entity\Figure;
use App\Entity\Comment;
use App\Form\FigureType;
use App\Form\CommentType;
use App\Repository\UserRepository;
use App\Repository\MediaRepository;
use App\Repository\FigureRepository;
use App\Repository\CommentRepository;
use App\Repository\CategoryRepository;
use Symfony\Component\HttpFoundation\Request;
use Doctrine\Common\Persistence\ObjectManager;
use Symfony\Component\Routing\Annotation\Route;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class FigureController extends AbstractController
{


    /**
     * @Route("/admin/supprime/{entity}/{id}", name="delete")
     */
    public function delete($entity, $id, FigureRepository $repoFigure, UserRepository $repoUser, MediaRepository $repoMedia, CategoryRepository $repoCategory, CommentRepository $repoComment, ObjectManager $manager)
    {
        if ($entity == 'user') {
            $user = $repoUser->find($id);
            $manager->remove($user);
        } elseif ($entity == 'figure') {
            $figure = $repoFigure->find($id);
            $manager->remove($figure);
        } elseif ($entity == 'category') {
            $category = $repoCategory->find($id);
            $manager->remove($category);
        } elseif ($entity == 'media') {
            $media = $repoMedia->find($id);
            $mediaRoute = $repoMedia->find($id);
            $manager->remove($media);
        } elseif ($entity == 'comment') {
            $comment = $repoComment->find($id);
            $commentRoute = $repoComment->find($id);
            $manager->remove($comment);
        }
        $manager->flush();

        if ($entity == 'figure') {
            return $this->redirectToRoute('home');
        } elseif ($entity == 'media') {
            return $this->redirectToRoute('figure_show', ['id' => $mediaRoute->getFigure()->getId()]);
        } elseif ($entity == 'category') {
            return $this->redirectToRoute('categoryAllView');
        } elseif ($entity == 'comment') {
            return $this->redirectToRoute('figure_show', ['id' => $commentRoute->getFigure()->getId()]);
        }
    }

    /**
     *  @Route("admin/figure/new", name="figure_create")
     *  @Route("admin/figure/{id}/edit", name="figure_edit")
     */
    public function formFigure(Figure $figure = null, Media $media = null, Request $request, ObjectManager $manager)
    {
        if (!$figure) {
            $figure = new Figure();
        }
        $user = $this->getUser();

        if (!$media) {
            $media = new Media();
        }

        $originalMedias = new ArrayCollection();

        foreach ($figure->getMedias() as $media) {
            $originalMedias->add($media);
        }

        $form = $this->createForm(FigureType::class, $figure);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            if (!$figure->getId()) {
                $figure->setDateCreated(new \DateTime());
            } else {
                $figure->setDateLastUpdate(new \Datetime());
            }
            $figure->setUser($user);
            $imageFile = $form['image']->getData();
            $mediaImages = $form['medias']->getData();

            if ($imageFile) {
                $newFileName = $this->generateUniqueFileName() . '.' . $imageFile->guessExtension();

                try {
                    $imageFile->move(
                        $this->getParameter('figuresImg_directory'),
                        $newFileName
                    );
                } catch (FileException $e) {
                    // ... handle exception if something happens during file upload
                }
                $figure->setImage($newFileName);
            }

            foreach ($mediaImages as $mediaImage) {
                $media->setFigure($figure);
                $manager->persist($mediaImage);
            }

            $manager->persist($user);
            $manager->persist($figure);
            $manager->flush();

            return $this->redirectToRoute('figure_show', ['id' => $figure->getid()]);
        }

        return $this->render('figure/figureForm.html.twig', [
            'formFigure' => $form->createView(),
            'editMode' => $figure->getId() !== null
        ]);
    }

    /**
     * @return string
     */
    private function generateUniqueFileName()
    {
        // md5() reduces the similarity of the file names generated by
        // uniqid(), which is based on timestamps
        return md5(uniqid());
    }

    /**
     * @Route("/", name="home")
     */
    public function index(FigureRepository $repo)
    {
        /* $figures = $repo->findBy(array(), array('id' => 'DESC'), 5); */
        $figures = $repo->findAll();
        $user = $this->getUser();

        return $this->render('index.html.twig', [
            'controller_name' => 'FigureController',
            'user' => $user,
            'figures' => $figures
        ]);
    }

    /**
     *  @Route("/figure/{id}", name="figure_show")
     */
    public function figureShow(Figure $figure, MediaRepository $repo, Request $request, ObjectManager $manager)
    {
        $figureComment = new Comment();
        $user = $this->getUser();

        $form = $this->createForm(CommentType::class, $figureComment);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $figureComment->setDateCreated(new \DateTime());
            $figureComment->setUser($user);
            $figureComment->setFigure($figure);

            $manager->persist($user);
            $manager->persist($figure);
            $manager->persist($figureComment);
            $manager->flush();

            return $this->redirectToRoute('figure_show', ['id' => $figure->getId()]);
        }

        $medias = $repo->findBy(array('figure' => $figure->getId()));

        return $this->render('figure/figureShow.html.twig', [
            'figure' => $figure,
            'user' => $user,
            'formComment' => $form->createView(),
            'medias' => $medias,
        ]);
    }
}
