<?php

namespace App\Controller;

use DateTime;
use DateInterval;
use App\Entity\User;
use App\Form\RegistrationType;
use App\Repository\UserRepository;
use Symfony\Component\HttpFoundation\Request;
use Doctrine\Common\Persistence\ObjectManager;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Security\Http\Authentication\AuthenticationUtils;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;

class SecurityController extends AbstractController
{

    /**
     * @Route("/inscription", name="security_registration")
     */
    public function registration(Request $request, ObjectManager $manager, UserPasswordEncoderInterface $encoder, \Swift_Mailer $mailer)
    {

        $user = $this->getUser();

        if (!$user) {
            $user = new User();
        }

        $form = $this->createForm(RegistrationType::class, $user);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $user->setDateCreated(new \DateTime());
            $user->setToken(rand());
            $user->setConfirm(false);

            $hash = $encoder->encodePassword($user, $user->getPassword());
            $user->setPassword($hash);

            $imageFile = $form['image']->getData();
            if ($imageFile) {
                $newFileName = $this->generateUniqueFileName() . '.' . $imageFile->guessExtension();

                try {
                    $imageFile->move(
                        $this->getParameter('UserImg_directory'),
                        $newFileName
                    );
                } catch (FileException $e) {
                    // ... handle exception if something happens during file upload
                }
                $user->setImage($newFileName);
            }

            $manager->persist($user);
            $manager->flush();

            $message = (new \Swift_Message('Mail de Confirmation'))
                ->setFrom('send@example.com')
                ->setTo($user->getEmail())
                ->setBody(
                    'Voici le lien pour confirmer votre compte : </br>
            http://localhost:8000/security/confirm/' . $user->getToken() . ' </br>
            Vous pouvez utiliser votre compte durant 24h sans confirmer l\'adresse email.',
                    'text/html'
                );

            $mailer->send($message);

            return $this->redirectToRoute('home');
        }

        return $this->render('security/registration.html.twig', [
            'form' => $form->createView()
        ]);
    }

    /**
     * @return string
     */
    private function generateUniqueFileName()
    {
        // md5() reduces the similarity of the file names generated by
        // uniqid(), which is based on timestamps
        return md5(uniqid());
    }

    /**
     * @Route("/security/confirm/{token}", name="confirmMail")
     */
    public function confirmation(User $user, ObjectManager $manager)
    {
        $user->setConfirm(true);
        $user->setToken(rand());
        $manager->persist($user);
        $manager->flush();

        return $this->render('security/mailConfirm.html.twig');
    }

    /** 
     * @Route("/connexion", name="security_login")
     */
    public function login(AuthenticationUtils $authUtils)
    {
        $error = $authUtils->getLastAuthenticationError();

        $lastUsername = $authUtils->getLastUsername();

        return $this->render('security/login.html.twig', [
            'last_username' => $lastUsername,
            'error'         => $error
        ]);
    }

    /**
     * @Route("/security/VerifyValid", name="verify_valid")
     */
    public function verifyValid(\Swift_Mailer $mailer)
    {
        $user = $this->getUser();
        $date = $user->getDateCreated();
        $date->add(new DateInterval('P1D'));
        $now = new DateTime();

        if ($user->getConfirm() == false && $date < $now) {
            $message = (new \Swift_Message('Mail de Confirmation'))
            ->setFrom('send@example.com')
            ->setTo($user->getEmail())
            ->setBody(
                'Cela fait 24h que vous n\'avez pas confirmer votre adresse email. Veuillez la confirmer si vous souhaitez vous connecter : </br>
        http://localhost:8000/security/confirm/' . $user->getToken() . '',
                'text/html'
            );

            $mailer->send($message);
            return $this->redirectToRoute('security_logout');
        }
        return $this->redirectToRoute('home');
    }


    /**
     * @Route("/deconnexion", name="security_logout")
     */
    public function logout()
    {
        throw new \Exeption('This sould never be reached!');
    }

    /**
     * @Route("/security/formEmail", name="formEmailForgot")
     */
    public function formEmail(UserRepository $repo, \Swift_Mailer $mailer, Request $request)
    {

        $form = $this->createFormBuilder()
            ->add('email', EmailType::class, [
                'label' => false
            ])
            ->getForm();

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $user = $repo->findOneByEmail($form["email"]->getData());
            $message = (new \Swift_Message('Mot de passe oublié'))
                ->setFrom('send@example.com')
                ->setTo($user->getEmail())
                ->setBody(
                    'Voici le lien pour confirmer votre compte : </br>
            http://localhost:8000/security/forgotPassword/' . $user->getToken() . '',
                    'text/html'
                );

            $mailer->send($message);

            return $this->redirectToRoute('home');
        }

        return $this->render('security/formMailForgot.html.twig', [
            'formEmail' => $form->createView()
        ]);
    }

    /**
     * @Route("/security/forgotPassword/{token}", name="forgotPassword")
     */
    public function forgotPassword(User $user, Request $request, ObjectManager $manager, UserPasswordEncoderInterface $encoder)
    {
        if ($user == null) {
            echo "ok";
        }

        $form = $this->createFormBuilder()
            ->add('password', PasswordType::class)
            ->add('passwordConfirm', PasswordType::class)
            ->getForm();

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            if ($form["password"]->getData() == $form["passwordConfirm"]->getData()) {
                $hash = $encoder->encodePassword($user, $form["password"]->getData());
                $user->setPassword($hash);
                $user->setToken(rand());

                $manager->persist($user);
                $manager->flush();
            } else {
                $error1 = true;

                return $this->render('security/forgotPassword.html.twig', [
                    'formPassword' => $form->createView(),
                    'error1' => $error1
                ]);
            }

            return $this->redirectToRoute('home');
        }

        $error1 = null;

        return $this->render('security/forgotPassword.html.twig', [
            'formPassword' => $form->createView(),
            'error1' => $error1
        ]);
    }

}
