#index:
#    path: /
#    controller: App\Controller\DefaultController::index
ajax_route:
    path:     /ajax_request
    defaults:
         _controller: AppBundle:Default:ajax
    methods: [post]
    
logout:
    path: /deconnexion

logout_noValidUser:
    path: /security/toConfirm
